### ISSUE TITLE
AGM A8 ?

### ISSUE THREAD

**Issue by JVD66** [zhaochengw/android_kernel_agm_agma3eu#1]
Sorry zhaochengw - this is the only way I could figure out 
to message you  : 

Please, RE: post on XDA Developers  : 
https://forum.xda-developers.com/general/device-reviews-and-information/agm-a8-rugged-info-msm8916-review-t3542052/page3#post71858823
[QUOTE=ffboy2009;71731077]
LineageOS 7.1 for AGM A8 has beed developed by myself:)
all things works like a charm
will release soon！
...
Mi Max hydrogen sources
https://github.com/zhaochengw?tab=repositories
[/QUOTE]

Please can you post the   name of   /  link to 
the correct repository to check out to build  lineageOS 14.1+
for AGM A8  ?  It has MSM8916 Snapdragon 410 chipset , which
is slightly different to the X1  .  
Is this the repository to check out to get A8 support ?

I am going to wait until one of these google searches returns some results:

> No results found for site:source.android.com "AGM A8"

> No results found for site:lineageos.org "AGM A8".

> No results found for ResurrectionRemix "AGM A8" git.

If there is a git, I will wait for one whose documentation is not in Russian / Chinese.

I am not an expert Android developer, and have one chance to get it right -
I cannot afford to brick my phone .

I will wait until some more expert Android developer with more test resources than me
has committed a repository that mentions somewhere in its English documentation
that the "AGM A8" platform IS supported. 

Please let me know when you commit the AGM A8 support and which repository it is in ! 

I promise not to bother you with lots of questions. I just need a working build to get started.
And I offer to help test things / fix things / report problems if desired.

Thanks & Regards,  
Jason Vas Dias  (github:JVD66) < jason.vas.dias@gmail.com >

**Comment by zhaochengw** [comment]
this is no source for A8 now
maybe AGM will release in few weeks,just wait plz
